[package]
name = "vsp-cli"
version = "0.1.0"
edition = "2021"

[dependencies]

  [dependencies.clap]
  workspace = true

  [dependencies.shlex]
  workspace = true

  [dependencies.vsp-error]
  path = "../error"
