[workspace]
members = [
  "ast",
  "bin",
  "cli",
#  "error",
  "mx",
  "lexer",
  "llvm",
  "platform",
  "pm",
  "span",
  "support",
]

[workspace.dependencies]
anyhow = "^1.0.66"
clap = "^4.0.25"
git2 = "^0.16.1"
inkwell = { version = "0.1.0-beta.5", features = [ "llvm14-0" ] }
nanoid = "^0.4.0"
serde = { version = "^1.0.147", features = [ "derive" ] }
