imports_layout = "Vertical"
imports_indent = "Block"
imports_granularity = "One"
newline_style = "Unix"
tab_spaces = 2
unstable_features = true
use_field_init_shorthand = true
use_try_shorthand = true
