group_imports = "StdExternalCrate"
imports_granularity = "Item"
newline_style = "Unix"
reorder_impl_items = true
reorder_imports = true
struct_field_align_threshold = 20
tab_spaces = 2
unstable_features = true
use_try_shorthand = true
wrap_comments = true
