[package]
name = "vsp-pm"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]

[dependencies]
anyhow.workspace = true
git2.workspace = true
serde.workspace = true
serde_yaml.workspace = true
#toml.workspace = true

vsp-error.path = "../error"
vsp-support.path = "../support"
