[package]
name = "vsp-dump"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

  [dependencies.vsp-ast-parser]
  path = "../ast-parser"

  [dependencies.vsp-error]
  path = "../error"
