[package]
name = "vsp-support"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow.workspace = true
clap.workspace = true
nanoid.workspace = true
semver.workspace = true
serde.workspace = true
target-lexicon.workspace = true
