[package]
name = "vsp-platform"
version = "0.1.0"
edition = "2021"

[dependencies]

    [dependencies.vsp-error]
    path = "../error"

[target.'cfg(unix)'.dependencies]
libc = "^0.2.137"

[target.'cfg(windows)'.dependencies]
winapi = "^0.3.9"
