[package]
name = "vsp-ast"
version = "0.1.0"
edition = "2021"

[dependencies]

    [dependencies.vsp-span]
    path = "../span"

    [dependencies.vsp-support]
    path = "../support"

    [dependencies.vsp-token]
    path = "../token"
