[package]
name = "vsp-ast-parser"
version = "0.1.0"
edition = "2021"

[dependencies]

    [dependencies.combine]
    workspace = true

    [dependencies.vsp-ast]
    path = "../ast"

    [dependencies.vsp-token]
    path = "../token"
