[package]
name = "vsp-ast-parser"
version = "0.1.0"
edition = "2021"

[dependencies]

  [dependencies.vsp-ast]
  path = "../ast"

  [dependencies.vsp-error]
  path = "../error"

  [dependencies.vsp-span]
  path = "../span"

  [dependencies.vsp-support]
  path = "../support"
