[package]
name = "vsp-ast-parser"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["rlib", "dylib"]

[dependencies]
# Workspace dependency
vsp-ast.path = "../ast"
vsp-parserc.path = "../parserc"
