[package]
name = "vsp-bin"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "vsp"
path = "src/main.rs"

[features]
default = []
compact = []
runtime = []
gui = []
container = []
dev-tools-only = []

[dependencies]
anyhow.workspace = true
clap.workspace = true
target-lexicon.workspace = true

# Workspace dependencies
vsp-cli.path = "../cli"
vsp-compiler.path = "../compiler"
vsp-dbg.path = "../dbg"
vsp-platform.path = "../platform"
vsp-pm.path = "../pm"
vsp-support.path = "../support"

[target.'cfg(target_os = "linux")']
rustflags = ["-C", "link-arg=-nostartfiles"]

[target.'cfg(target_os = "windows")']
rustflags = ["-C", "link-args=/ENTRY:_start /SUBSYSTEM:console"]

[target.'cfg(target_os = "macos")']
rustflags = ["-C", "link-args=-e __start -static -nostartfiles"]

[target.'cfg(target_env = "musl")']
rustflags = ["-C", "target-feature=+crt-static"]
