[package]
name = "vsp-bin"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "vsp"
path = "src/main.rs"

[features]
default = []
compact = []
runtime = []
gui = []
container = []
dev-tools-only = []

[dependencies]

    [dependencies.anstyle]
    workspace = true

    [dependencies.clap]
    workspace = true

    [dependencies.target-lexicon]
    workspace = true

    [dependencies.vsp-cli]
    path = "../cli"

    [dependencies.vsp-compiler]
    path = "../compiler"

    [dependencies.vsp-dbg]
    path = "../debugger"

    [dependencies.vsp-error]
    path = "../error"

    [dependencies.vsp-lsp]
    path = "../lsp"

    [dependencies.vsp-platform]
    path = "../platform"

    [dependencies.vsp-pm]
    path = "../pm"

    [dependencies.vsp-support]
    path = "../support"

[target.'cfg(target_os = "linux")']
rustflags = ["-C", "link-arg=-nostartfiles"]

[target.'cfg(target_os = "windows")']
rustflags = ["-C", "link-args=/ENTRY:_start /SUBSYSTEM:console"]

[target.'cfg(target_os = "macos")']
rustflags = ["-C", "link-args=-e __start -static -nostartfiles"]

[target.'cfg(target_env = "musl")']
rustflags = ["-C", "target-feature=+crt-static"]
