[package]
name = "vsp-bin"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "vsp"
path = "src/main.rs"

[features]
default = []
compact = []
runtime = []

[dependencies]
anyhow.workspace = true
clap.workspace = true
# Workspace dependencies
vsp-cli.path = "../cli"
vsp-mx.path = "../mx"
vsp-pm.path = "../pm"
vsp-support.path = "../support"

[build-dependencies]
clap.workspace = true
clap_complete.workspace = true

#[target.'cfg(target_os = "linux")']
#rustflags = ["-C", "link-arg=-nostartfiles"]
#
#[target.'cfg(target_os = "windows")']
#rustflags = ["-C", "link-args=/ENTRY:_start /SUBSYSTEM:console"]
#
#[target.'cfg(target_os = "macos")']
#rustflags = ["-C", "link-args=-e __start -static -nostartfiles"]

[profile.release]
opt-level = 3
