[package]
name = "vsp-bin"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "vsp"
path = "src/main.rs"

[features]
default = []
compact = []
runtime = []

[dependencies]
anyhow.workspace = true
clap.workspace = true
# Workspace dependencies
vsp-cli.path = "../cli"
vsp-mx.path = "../mx"
vsp-pm.path = "../pm"
vsp-support.path = "../support"
