[package]
name = "vsp-mx"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]

[dependencies]
anyhow.workspace = true

vsp-cli = { path = "../vsp-cli" }
vsp-platform = { path = "../vsp-platform" }
